api/urls.py
from django.urls import path
from api import views

urlpatterns = [
    path('values/', views.data_list),
    path('values/<int:pk>/', views.data_detail),
    path('form/<int:pk>/', views.form_data),
    path('form/<int:pk>/id/<int:person_id>/', views.person_form_data),
    path('qid/<int:question_id>/', views.question_form_data),
    path('question/<int:pk>/', views.form_question),
    path('choices/<int:pk>/', views.question_choices),
    path('type/<int:pk>/id/<int:person_id>/', views.person_data),
    path('type/<int:pk>/id/<int:person_id>/template', views.index),
    path('test', views.trypost),
    path('detail/<int:form_id>', views.detail),
]

formentry/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from . import formviews

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^datamode/$', views.entry, name='entry'),
    # url(r'^datamode/<int:person>/person/(?P<house>[0-9]+)/$', views.entry, name='personid'),
    path('datamode/<int:person>/person/', views.entry, name='personid'),
    url(r'^people/$', views.all_people, name='people'),
    # url(r'^(?P<person_id>[0-9]+)/$', views.detail, name='detail'),
        path('people/<int:status>/stat/', views.all_people, name='people_status'),
        

    path('geo/<int:id>/', views.geo_entry, name='geo'),
        path('house/<int:geo>/<int:pid>/house/',views.house_entry, name='house_entry'),
            path('house/<int:coordinates>/<int:pid>/head/', views.house_head_entry, name='house_head'),
        path('family/<int:house>/<int:fid>/family/<int:geo>/coordinates/<int:pid>/person', views.family_entry, name='family_details'),
        path('relation/<int:mooli>/<int:child>/<int:entry>/', views.relation_entry, name='relation'),
    # # path('')

    path('family/<int:geo>/coordinate/',views.family_list,name='family_list'),
    path('family/<int:family_id>/members', views.member_list, name="memberlist"),

    path('myform/<int:form_id>/member/<int:member>/marktype/<int:mark>/<int:marker>/', formviews.mainforms, name='form_basic'),
    path('myform/all_forms', formviews.all_my_forms, name='all_my_forms'),
    path('userforms/<int:member>/type/<int:memtype>', formviews.all_member_forms, name='memberforms'),
        path('deleteform/<int:form_id>/member/<int:member>/marktype/<int:mark>/<int:marker>/', formviews.deleteforms, name='deleteforms'),
        path('printform/<int:form_id>/member/<int:member>/marktype/<int:mark>/<int:marker>/', formviews.printforms, name='printforms'),
        path('myform/print_forms', formviews.print_my_forms, name='print_my_forms'),
        path('myform/delete_forms', formviews.delete_my_forms, name='delete_my_forms'),
        path('delete/<int:id>/type/<int:del_type>/', formviews.deleteEntry, name='delete_entry'),

    url(r'^design/$', formviews.index, name='form_index'),
    path('design/<int:id>/main/', formviews.formindex, name='submit_formindex'),
    path('design/<int:id>/table/', formviews.tableindex, name='table_index'),
    path('design/<int:formid>/form/<int:tid>/mytable/', formviews.submit_tableindex, name='submit_tableindex'),
    path('design/<int:id>/question/', formviews.questionindex, name='question_index'),
    path('design/<int:tid>/table/<int:qid>/myquestion/', formviews.submit_questionindex, name='submit_questionindex'),
    path('design/<int:id>/choice/', formviews.choiceindex, name='choice_index'),
    path('design/<int:qid>/question/<int:cid>/mychoice/', formviews.submit_choiceindex, name='submit_choiceindex'),

    path('houses/', views.all_my_houses, name='all_my_houses'),

    # moved testing to new app: postform
    # path('design/test', formviews.seePost, name="testing"),

]

#Namespacing URL Names
app_name = "formentry"

parbatcms/urls.py
from django.conf.urls import include, url
# from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from formentry import views



urlpatterns = [
    # url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    # url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^personal/', include('personal.urls')),
    url(r'^forms/', include('formentry.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^post/', include('postform.urls')),
    # url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^$', views.index, name='index'),
    # url(r'^ajax/', include('mydajax.urls')),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postform/urls.py
from django.conf.urls import url
from django.urls import path
from photouploads import photoviews
from . import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # url(r'^datamode/$', views.entry, name='entry'),
    path('data', views.makePost, name='saveposts'),
    path('design/test', views.seePost, name="seepost"),
    path('uploads/<int:member>/<int:memberType>', photoviews.simple_upload, name="upload")
]

#Namespacing URL Names
app_name = "postform"

users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    # url(r'^(?P<person_id>[0-9]+)/$', views.detail, name='detail'),
    # path('<int:person_id>/', views.detail, name='vote'),
]

#Namespacing URL Names
app_name = "users"

formentry/forms.py
from django.forms import ModelForm, DateTimeInput, HiddenInput, Textarea
from personal.models import *

class PersonalForm(ModelForm):
    def __init__(self, *args, **kwargs):
       self.request = kwargs.pop('request', None)
       return super(PersonalForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Personal
        exclude = ['gened']
        fields = '__all__'
        # widgets = {
        #     'name': Textarea(attrs={'cols': 80, 'rows': 20}),
        # }
        field_classes = {
            # 'slug': MySlugFormField,
            'hari':'freaks', 'class':'form-control'
        }
        widgets = {
            'pub_date': DateTimeInput(attrs={'class': 'datetime-input'}),
            'creator' : Textarea(attrs={'disabled':'True'}),
        }


class HouseForm(ModelForm):
    class Meta:
        model = House
        fields = '__all__'

class GeoForm(ModelForm):
    class Meta:
        model = GeoCode
        fields = '__all__'

class FamilyForm(ModelForm):
    class Meta:
        model = Family
        fields = '__all__'

class RelationForm(ModelForm):
    class Meta:
        model = Relation
        fields = '__all__'

formentry/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.contrib.auth.decorators import login_required

from .forms import *
from django.http import Http404


# Create your views here.
@login_required(login_url='users:login')
def index(request):
    sql = 'SELECT COUNT(id) as id FROM personal_personal'
    total_person = Personal.objects.raw(sql)[0].id
    sql = 'SELECT COUNT(id) as id FROM personal_personal WHERE gender=1'
    total_male = Personal.objects.raw(sql)[0].id
    sql = 'SELECT COUNT(id) as id FROM personal_personal WHERE gender=2'
    total_female = Personal.objects.raw(sql)[0].id
    sql = 'SELECT COUNT(id) as id FROM personal_personal WHERE gender=3'
    total_third = Personal.objects.raw(sql)[0].id
    sql = 'SELECT COUNT(id) as id FROM personal_personal WHERE gender=4'
    total_other = Personal.objects.raw(sql)[0].id

    sql = 'SELECT COUNT(id) as id FROM personal_family WHERE 1'
    total_family = Personal.objects.raw(sql)[0].id
    sql = 'SELECT COUNT(id) as id FROM personal_house WHERE 1'
    total_house = Personal.objects.raw(sql)[0].id


    context = { 'total_person':total_person, 'total_male':total_male, 'total_female':total_female, 'total_third':total_third, 'total_other':total_other, 'total_family':total_family, 'total_house':total_house,

    }
    return render(request, 'design/index.html', context)
    #2 return HttpResponse(template.render(context, request))

@login_required(login_url='users:login')
def entry(request, person=0,house=None):
    request.session['myurl'] = request.path

    if person!=0:
        my_person = Personal.objects.get(pk = int(person))
        form = PersonalForm(request.POST or None, instance=my_person)
    else:
        form = PersonalForm(request.POST or None)
    if form.is_valid():
        person_saved = form.save()
        return redirect('formentry:people_status', status=1)
    return render(request, 'design/forms.html',{'form':form, 'user':request.user, 'personid':person, 'houseid':house})

@login_required(login_url='users:login')
def all_people(request, status=0):
    request.session['myurl'] = request.path
    a = Personal.objects.all()
    if status==1:
        status_name = "Saved"
    else:
        status_name = None
    return render(request, 'design/all.html', {'user':request.user,  'status':status_name, 'all':a})


@login_required(login_url='users:login')
def geo_entry(request, id=0):
    request.session['myurl'] = request.path
    if id !=0 :
        my_geo = GeoCode.objects.get(pk=int(id))
        form = GeoForm(request.POST or None, instance=my_geo)
    else:
        form = GeoForm(request.POST or None)
    if form.is_valid():
        geo_saved = form.save()
        return redirect('formentry:house_entry',geo=geo_saved.id, pid=0)
    return render (request,'entry_forms/geo.html',{'form':form, 'geoid':id})

@login_required(login_url='users:login')
def house_entry(request,geo=0, pid=0 ):
    request.session['myurl'] = request.path
    coordinate = GeoCode(pk=geo)
    try:
        my_house = House.objects.get(coordinates=coordinate)
        form = HouseForm(request.POST or None, instance=my_house)
    except House.DoesNotExist:
        if pid ==0:
            return redirect('formentry:family_details', house=0,  fid=0, geo=geo, pid=0)
        owner = Family(id=pid)
        my_house = House(coordinates=coordinate, owner=owner)
        form = HouseForm(request.POST or None, instance=my_house)
    add_others = True
    if form.is_valid():
        house_saved = form.save()
        return redirect('formentry:family_list', geo=geo)
    return render (request, 'entry_forms/house.html', {'form':form, 'personid':pid, 'geoid':geo, 'add_others':add_others})

@login_required(login_url='users:login')
def family_entry(request, house=0, fid=0, geo=0, pid=0):
    #fid = family head
    #pid = family person... if fid doesn't exist pid becomes main head
    request.session['myurl'] = request.path
    if fid==0:
        return redirect('formentry:house_head', coordinates=geo, pid=0)
    try:
        # family_head = Personal(id=fid)
        my_family = Family.objects.get(id=fid)
        # if my_family:
        #     return redirect('formentry:house_head', coordinates=geo, pid=0)
        if (request.POST or None) == None:
            return redirect('formentry:memberlist', family_id=fid)
        form = FamilyForm(request.POST or None, instance=my_family)
    except Family.DoesNotExist:
        family_head = Personal(id=fid)
        my_family = Family(person_head=family_head, myhouse=GeoCode(id=geo))
        form = FamilyForm(request.POST or None, instance=my_family)
    try:
        house_families = Family.objects.filter(myhouse=house)
    except:
        house_families = None
    if form.is_valid():
        family_saved =form.save()
        if house==0:
            return redirect ('formentry:house_entry', geo=geo, pid=family_saved.id)
        else:
            return redirect('formentry:family_details', house=house, fid=fid, geo=geo, pid=pid)
    return render(request, 'entry_forms/family.html',{'form':form, 'families':house_families, 'geo':geo, 'house':house, 'pid':pid, 'fid':fid})

@login_required(login_url='users:login')
def house_head_entry(request,coordinates=0, pid=0):
    request.session['myurl'] = request.path

    if pid != 0:
        my_person = Personal.objects.get(pk = int(pid))
        form = PersonalForm(request.POST or None, instance=my_person)
    else:
        form = PersonalForm(request.POST or None, request=request)
    if form.is_valid():
        person_saved = form.save(commit=False)
        person_saved.creator = request.user.username
        person_saved.save()
        return redirect('formentry:family_details', house=0, fid=person_saved.id, geo=coordinates, pid =0)

    # request.session['myurl'] = request.path
    return render(request, 'entry_forms/user_forms.html',{'form':form, 'user':request.user, 'personid':pid, 'geo':coordinates, 'form_next':'house'})

@login_required(login_url='users:login')
def family_list(request, geo):
    request.session['myurl'] = request.path

    GeoObject = GeoCode.objects.get(pk=geo)
    theHouse = House.objects.get(coordinates=GeoObject)
    # request.session['myurl'] = request.path
    ListofFamilies = Family.objects.filter(myhouse=GeoObject)
    return render(request, 'entry_forms/family_list.html',{
        'families':ListofFamilies,
        'geo':geo,
        'request':request,
        'house':theHouse,
    })


@login_required(login_url='users:login')
def member_list(request, family_id):
    request.session['myurl'] = request.path

    my_family = Family.objects.get(pk=family_id)
    request.session['myurl'] = request.path
    head = my_family.person_head
    try:
        ListofMembers = Relation.objects.filter(family=my_family)
    except Relation.DoesNotExist:
        ListofMembers = {}
    geo = my_family.myhouse.id # To reference back to family from member_list.html
    return render(request, 'entry_forms/family_member_list.html',{'members':ListofMembers, 'mooli':my_family.id, 'geo' : geo , 'head':head })

@login_required(login_url='users:login')
def relation_entry(request,mooli=0,child=0, entry=0):
    request.session['myurl'] = request.path

    try:
        mool_family = Family.objects.get(id=mooli)
        family_child = Personal.objects.get(id=child)
        if entry==0:
            form = PersonalForm(request.POST or None, instance=family_child)
            if form.is_valid():
                saved_entry = form.save()
                # message = "Saved"
            return render(request, 'entry_forms/user_forms.html',{'form':form, 'user':request.user, 'child':child, 'mooli':mooli, 'flag':'relation', 'personid':child,
            # 'message':message,
            })
    except Personal.DoesNotExist:
        form = PersonalForm(request.POST or None, request=request)
        if form.is_valid():
            # New Entry of PersonalForm
            # form = PersonForm(request.POST or None)
            saved_entry = form.save()
            return redirect('formentry:relation', mooli=mooli, child=saved_entry.id, entry=1)
        return render(request, 'entry_forms/user_forms.html',{'form':form, 'user':request.user, 'mooli':mooli, 'child':child, 'flag':'relation' })

    try:
        my_relation = Relation.objects.get(family=mool_family, person2=family_child)
        form = RelationForm(request.POST or None, instance=my_relation)
    except Relation.DoesNotExist:
        my_relation = Relation(family=mool_family, person2 =family_child)
        form = RelationForm(request.POST or None, instance=my_relation)
    if form.is_valid():
        relation_saved = form.save()
        return redirect('formentry:relation', mooli=mooli,  child=child, entry=0)
    return render(request, 'entry_forms/relation.html',{'form':form, 'mooli':mooli, 'child':child, 'entry':2})

@login_required(login_url='users:login')
def all_my_houses(request):
    request.session['myurl'] = request.path

    Houses = House.objects.all()
    # request.session['myurl'] = request.path
    HouseList = House.objects.all()
    return render(request, 'entry_forms/houselist.html',{'houses':HouseList, 'request':request})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth import login, logout


# Create your views here.
def index(request):
    context = {}
    return render(request,'users/index.html',context)


def login_view(request):
    #Loggin in the UsersConfig
    if request.method=='POST':
        #Do sth
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('formentry:index')

    else:
        #instantiate
        form = AuthenticationForm()

    return render(request,'users/index2.html',{'form':form})

def signup_view(request):
    # #Signup new user
    if request.method=='POST':
        #Do sth
        # logger.error('This was valid bro')
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # user = form.get_user
            login(request, user)
            return redirect('personal:index')

    else:
        #instantiate
        form = UserCreationForm()
        # form = 'This page is under Construction'

    return render(request,'users/index2.html',{'form':form})

def logout_view(request):
    logout(request)
    return redirect('users:login')

formentry/templates/entry_forms/family.html
{% extends 'entry_forms/user_forms.html' %}

{% block form-title %}
  <h4 class="card-title">परिवारको विवररण</h4>
  <p class="card-category">परिवार</p>
{% endblock %}

{% block form-body %}
<form action="{% url 'formentry:family_details' house=house fid=fid geo=geo pid=pid %}" method=post>
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" name="submit" value="Submit">
</form>
{% endblock %}

{% block form-footer %}

{% endblock %}

{% block form-nav %}
<a href="{% url 'formentry:memberlist' family_id=fid %}" class="btn btn-primary">View Family Members</a>
{% endblock %}

formentry/templates/entry_forms/family_list.html
{% extends 'entry_forms/user_forms.html' %}

{% block form-title %}
  <h4 class="card-title">घरका परिवारहरुको विवररण</h4>
  <p class="card-category">सबै परिवारका घरमुली</p>
{% endblock %}

{% block form-body %}
{% for member in families %}
<p><a href="{% url 'formentry:family_details' fid=member.id geo=geo pid=0 house=1 %}" class="btn btn-primary">{{member}}</a></p>
{% endfor %}
{% endblock %}

{% block form-footer %}

{% endblock %}

{% block form-nav %}
<a href="{% url 'formentry:family_details' geo=geo fid=0 pid=0 house=0%}" role="button" class="btn btn-primary">नयाँ परिवार थप्नुहोस् </a>
<a class="btn btn-primary" href="{% url 'formentry:memberforms' member=geo memtype=1 %}" role="button">Add More Details</a>
{% endblock %}

formentry/templates/entry_forms/family_member_list.html
{% extends 'entry_forms/user_forms.html' %}

{% block form-title %}
  <h4 class="card-title">परिवारका सदस्यहरुको विवरण</h4>
  <p class="card-category">परिवार सदस्य</p>
{% endblock %}

{% block form-body %}
<h1> <a href="{% url 'formentry:relation' mooli=mooli child=head.id entry=0 %}" class="btn btn-primary">{{head}}</a> </h1>
{% for member in members %}
<p> <a href="{% url 'formentry:relation' mooli=member.family.id child=member.person2.id  entry=0 %}" class="btn btn-danger">{{member.person2.full_name}}</a></p>
{% endfor %}
<!-- <p> <a href="{% url 'formentry:relation' mooli=mooli child=head.id  entry=0 %}" class="btn btn-danger">{{head.full_name}}</a></p> -->
{% endblock %}

{% block form-footer %}

{% endblock %}

{% block form-nav %}
<a href="{%url 'formentry:relation' mooli=mooli child=0 entry=0 %}" class="btn btn-primary">नयाँ सदस्य</a>
<a href="{%url 'formentry:family_list' geo=geo %}" class="btn btn-primary">घरमा फर्कनुहोस् ।</a>
<a class="btn btn-primary" href="{% url 'formentry:memberforms' member=mooli memtype=2 %}" role="button">Add More Details</a>
{% endblock %}

formentry/templates/entry_forms/geo.html
{% extends 'design/index.html' %}

{% load widget_tweaks %}

{% block content %}

<p>Click the button to get your coordinates.</p>

<button onclick="getLocation()">कृपया Click गर्नुहोस् </button>

<p id="demo"></p>
<form class="" action="{% url 'formentry:geo' id=geoid %}" method="post">
  {{form}}
  {% csrf_token %}
  <input type="submit" name="Submit" value="Submit">
</form>
<script>
var x = document.getElementById("demo");
var lat = document.getElementById("id_latitude");
var long = document.getElementById("id_longitude");

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.watchPosition(showPosition);
    } else {
        x.innerHTML = "Geolocation is not supported by this browser.";}
    }

function showPosition(position) {
    x.innerHTML="Latitude: " + position.coords.latitude +
    "<br>Longitude: " + position.coords.longitude;
    lat.value = position.coords.latitude;
    long.value = position.coords.longitude;

}
</script>
{% if id %}
  <a class="btn btn-primary" href="{% url 'formentry:house_person_entry' geo=geoid %}" role="button">Add House In This Coordinates</a>
{% endif %}

{% endblock %}

formentry/templates/entry_forms/house.html
{% extends 'design/index.html' %}

{% load widget_tweaks %}

{% block content %}
  <div class="row">
      <div class="col-md-12">
          <div class="card ">
              <div class="card-header ">
                  <h4 class="card-title">घरको अवस्था</h4>
                  <p class="card-category">घर मुलीहरुको विवरण</p>
              </div>
              <div class="card-body ">
                  <div id="form" >
                    {% block form-body %}
                    <form action="{% url 'formentry:house_entry' geo=geoid pid=personid %}" method="post">
                      {% csrf_token %}
                      {% for field in form %}
                        <div class="form-group">
                            {{ field.errors }}
                            {{ field.label_tag }}
                            {% if field.name != 'pub_date' %}
                              {{ field |attr:"class:form-control" }}
                            {% else %}
                              {{ field |attr:"class:datetime-input form-control" }}
                            {% endif %}
                            {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}
                        </div>
                    {% endfor %}

                    <input type="submit" value="submit"/>
                    {% endblock %}
                  </form>
                  </div>
              </div>
              <div class="card-footer ">
                  <div class="legend">
                      <i class="fa fa-circle text-info"></i> Open
                      <i class="fa fa-circle text-danger"></i> Bounce
                      <i class="fa fa-circle text-warning"></i> Unsubscribe
                  </div>
                  <hr>
                  <div class="stats">
                      <i class="fa fa-clock-o"></i> Campaign sent 2 days ago
                  </div>
              </div>
            </div>
          <div>
      </div>
  </div>
</div>
{% endblock %}

{% block nav %}
  <li >
      <a class="nav-link" href="{% url 'formentry:index' %}">
          <i class="nc-icon nc-chart-pie-35"></i>
          <p>Dashboard</p>
      </a>
  </li>
  <li class="nav-item active">
      <a class="nav-link" href="{% url 'formentry:entry'%}">
          <i class="nc-icon nc-circle-09"></i>
          <p>User Profile</p>
      </a>
  </li>
{% endblock %}

formentry/templates/entry_forms/houselist.html
{% extends 'entry_forms/user_forms.html' %}

{% block form-title %}
  <h4 class="card-title">सबै घर</h4>
  <p class="card-category">सबै घरका घरमुली</p>
{% endblock %}

{% block form-body %}
{% for member in houses %}
<p><a href="{% url 'formentry:family_list' geo=member.coordinates.id %}" class="btn btn-primary">{{member.owner}}</a></p>
{% endfor %}
{% endblock %}

{% block form-footer %}

{% endblock %}

{% block form-nav %}
<a href="{% url 'formentry:geo' id=0 %}" role="button" class="btn btn-primary">नयाँ घर थप्नुहोस् </a>
{% endblock %}

formentry/templates/entry_forms/relation.html
{% extends 'entry_forms/user_forms.html' %}

{% block form-title %}
  <h4 class="card-title">परिवारको विवररण</h4>
  <p class="card-category">सबै परिवार</p>
{% endblock %}

{% block form-body %}
<form action="{% url 'formentry:relation' mooli=mooli child=child entry=entry %}" method=post>
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" name="submit" value="Submit">
</form>
{% endblock %}

{% block form-footer %}

{% endblock %}

{% block form-nav %}
<p><a href="{%url 'formentry:relation' mooli=mooli child=0 entry=0 %}" class="btn btn-primary">नयाँ सदस्य थप्नुहोस्</a></p>
<p><a href="{%url 'formentry:relation' mooli=mooli child=child entry=0 %}" class="btn btn-primary">सदस्यको जानकारी थप्नुहोस्</a></p>
{% endblock %}

formentry/templates/entry_forms/user_forms.html
{% extends 'design/index.html' %}

{% load widget_tweaks %}

{% block content %}
  <div class="row">
      <div class="col-lg-8">
          <div class="card ">
              <div class="card-header ">{% block form-title %}
                  <h4 class="card-title">User Forms</h4>
                  <p class="card-category">
                    {% if form_next == 'house' %}
                      Enter the House Head Details
                    {% endif %}
                    {% if flag == 'relation' %}
                      घरका सदस्यहरुको सुचना राख्नुहोस् ।
                    {% endif %}
                  </p>{% endblock %}
              </div>

              <div class="card-body ">
                  <div id="form" >
                    {% block form-body %}
                    {% if form_next == 'house' %}
                      <form action="{% url 'formentry:house_head' pid=personid coordinates=geo %}" method="post">
                    {% endif %}
                    {% if flag == 'relation' %}
                      <form action="{% url 'formentry:relation' mooli=mooli child=child entry=0 %}" method="post">
                    {% endif %}
                      {% csrf_token %}
                      {% for field in form %}
                        <div class="form-group">
                            {{ field.errors }}
                            {{ field.label_tag }}
                            {% if field.name != 'pub_date' %}
                              {{ field |attr:"class:form-control" }}
                            {% else %}
                              {{ field |attr:"class:datetime-input form-control" }}
                            {% endif %}
                            {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}
                        </div>
                    {% endfor %}

                    <input type="submit" value="submit"/>
                  </form>{% endblock %}
                  </div>
              </div>
              <div class="card-footer ">{% block form-footer %}
                  <div class="legend">
                    {% if personid %}
                    <a class="btn btn-primary" href="{% url 'formentry:memberforms' member=personid memtype=3 %}" role="button">Add More Details</a>
                    {% endif %}
                  </div>
                {% endblock %}
              </div>
            </div>
          </div>
      <div class="col-lg-4">
          <div class="card ">
              <div class="card-header ">
                  <h4 class="card-title">Navigations</h4>

                </div>
                <div class="card-body">{% block form-nav %}
                  <!-- {% if form_next == 'house' %}
                    <a class = "btn btn-primary" href ="{% url 'formentry:family_details' geo=geo pid=0 house=0 fid=personid%}" role="button">पछाडी फर्कनुहोस्</a>
                  {% endif %} -->
                  {% if flag %}
                  {% if  personid %}
                    <a class = "btn btn-primary" href ="{% url 'formentry:relation' mooli=mooli child=child entry=2 %}" role="button">Add Relation</a>
                    <a class = "btn btn-primary" href ="{% url 'formentry:memberlist' family_id=mooli %}" role="button">परिवारमा जानुहोस् ।</a>
                    <a class= "btn btn-secondary" href="{% url 'postform:upload' member=child memberType=3 %}">फोटो खिच्नुहोस्</a>
                  {% endif %}
                  {% endif %}
                  {% endblock %}
              </div>
          <div class="card-footer">
          </div>
      </div>
  </div>
{% endblock %}

formentry/templates/entry_forms/user_general.html
{% extends 'entry_forms/user_forms.html' %}

{% block form-title %}
  <h4 class="card-title">{{formtitle}}</h4>
  <p class="card-category">{{formsubtitle}}</p>
{% endblock %}

{% block form-body %}
<form action="{{url}}" method="post">
  {% csrf_token %}
  {% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        {{ field.label_tag }}
        {% if field.name != 'pub_date' %}
          {{ field |attr:"class:form-control" }}
        {% else %}
          {{ field |attr:"class:datetime-input form-control" }}
        {% endif %}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}
</form>
{% endblock %}

{% block form-footer %}

{% endblock %}

{% block form-nav %}
<a href="{{back_url}}">पछाडी फर्कनुहोस्</a>
{% endblock %}