api/urls.py
from django.urls import path
from api import views

urlpatterns = [
    path('values/', views.data_list),
    path('values/<int:pk>/', views.data_detail),
    path('form/<int:pk>/', views.form_data),
    path('form/<int:pk>/id/<int:person_id>/', views.person_form_data),
    path('qid/<int:question_id>/', views.question_form_data),
    path('question/<int:pk>/', views.form_question),
    path('choices/<int:pk>/', views.question_choices),
    path('type/<int:pk>/id/<int:person_id>/', views.person_data),
    path('type/<int:pk>/id/<int:person_id>/template', views.index),
    path('test', views.trypost),
    path('detail/<int:form_id>', views.detail),
]

formentry/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from . import formviews

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^datamode/$', views.entry, name='entry'),
    # url(r'^datamode/<int:person>/person/(?P<house>[0-9]+)/$', views.entry, name='personid'),
    path('datamode/<int:person>/person/', views.entry, name='personid'),
    url(r'^people/$', views.all_people, name='people'),
    # url(r'^(?P<person_id>[0-9]+)/$', views.detail, name='detail'),
        path('people/<int:status>/stat/', views.all_people, name='people_status'),
        

    path('geo/<int:id>/', views.geo_entry, name='geo'),
        path('house/<int:geo>/<int:pid>/house/',views.house_entry, name='house_entry'),
            path('house/<int:coordinates>/<int:pid>/head/', views.house_head_entry, name='house_head'),
        path('family/<int:house>/<int:fid>/family/<int:geo>/coordinates/<int:pid>/person', views.family_entry, name='family_details'),
        path('relation/<int:mooli>/<int:child>/<int:entry>/', views.relation_entry, name='relation'),
    # # path('')

    path('family/<int:geo>/coordinate/',views.family_list,name='family_list'),
    path('family/<int:family_id>/members', views.member_list, name="memberlist"),

    path('myform/<int:form_id>/member/<int:member>/marktype/<int:mark>/<int:marker>/', formviews.mainforms, name='form_basic'),
    path('myform/all_forms', formviews.all_my_forms, name='all_my_forms'),
    path('userforms/<int:member>/type/<int:memtype>', formviews.all_member_forms, name='memberforms'),
        path('deleteform/<int:form_id>/member/<int:member>/marktype/<int:mark>/<int:marker>/', formviews.deleteforms, name='deleteforms'),
        path('printform/<int:form_id>/member/<int:member>/marktype/<int:mark>/<int:marker>/', formviews.printforms, name='printforms'),
        path('myform/print_forms', formviews.print_my_forms, name='print_my_forms'),
        path('myform/delete_forms', formviews.delete_my_forms, name='delete_my_forms'),
        path('delete/<int:id>/type/<int:del_type>/', formviews.deleteEntry, name='delete_entry'),

    url(r'^design/$', formviews.index, name='form_index'),
    path('design/<int:id>/main/', formviews.formindex, name='submit_formindex'),
    path('design/<int:id>/table/', formviews.tableindex, name='table_index'),
    path('design/<int:formid>/form/<int:tid>/mytable/', formviews.submit_tableindex, name='submit_tableindex'),
    path('design/<int:id>/question/', formviews.questionindex, name='question_index'),
    path('design/<int:tid>/table/<int:qid>/myquestion/', formviews.submit_questionindex, name='submit_questionindex'),
    path('design/<int:id>/choice/', formviews.choiceindex, name='choice_index'),
    path('design/<int:qid>/question/<int:cid>/mychoice/', formviews.submit_choiceindex, name='submit_choiceindex'),

    path('houses/', views.all_my_houses, name='all_my_houses'),

    # moved testing to new app: postform
    # path('design/test', formviews.seePost, name="testing"),

]

#Namespacing URL Names
app_name = "formentry"

parbatcms/urls.py
from django.conf.urls import include, url
# from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from formentry import views



urlpatterns = [
    # url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    # url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^personal/', include('personal.urls')),
    url(r'^forms/', include('formentry.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^post/', include('postform.urls')),
    # url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^$', views.index, name='index'),
    # url(r'^ajax/', include('mydajax.urls')),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    # url(r'^(?P<person_id>[0-9]+)/$', views.detail, name='detail'),
    # path('<int:person_id>/', views.detail, name='vote'),
]

#Namespacing URL Names
app_name = "users"

formentry/models.py
from django.db import models

# Create your models here.
# from formentry.submodals.formGenerator import *
from formentry.submodals.formGenerator import *

users/models.py
from django.db import models

# Create your models here.

class FormUser(models.Model):
    username = models.CharField('Username', max_length=20)
    password = models.CharField('Password', max_length=70)

formentry/forms.py
from django.forms import ModelForm, DateTimeInput, HiddenInput, Textarea
from personal.models import *

class PersonalForm(ModelForm):
    def __init__(self, *args, **kwargs):
       self.request = kwargs.pop('request', None)
       return super(PersonalForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Personal
        exclude = ['gened']
        fields = '__all__'
        # widgets = {
        #     'name': Textarea(attrs={'cols': 80, 'rows': 20}),
        # }
        field_classes = {
            # 'slug': MySlugFormField,
            'hari':'freaks', 'class':'form-control'
        }
        widgets = {
            'pub_date': DateTimeInput(attrs={'class': 'datetime-input'}),
            'creator' : Textarea(attrs={'disabled':'True'}),
        }


class HouseForm(ModelForm):
    class Meta:
        model = House
        fields = '__all__'

class GeoForm(ModelForm):
    class Meta:
        model = GeoCode
        fields = '__all__'

class FamilyForm(ModelForm):
    class Meta:
        model = Family
        fields = '__all__'

class RelationForm(ModelForm):
    class Meta:
        model = Relation
        fields = '__all__'

formentry/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.contrib.auth.decorators import login_required

from .forms import *
from django.http import Http404


# Create your views here.
@login_required(login_url='users:login')
def index(request):
    sql = 'SELECT COUNT(id) as id FROM personal_personal'
    total_person = Personal.objects.raw(sql)[0].id
    sql = 'SELECT COUNT(id) as id FROM personal_personal WHERE gender=1'
    total_male = Personal.objects.raw(sql)[0].id
    sql = 'SELECT COUNT(id) as id FROM personal_personal WHERE gender=2'
    total_female = Personal.objects.raw(sql)[0].id
    sql = 'SELECT COUNT(id) as id FROM personal_personal WHERE gender=3'
    total_third = Personal.objects.raw(sql)[0].id
    sql = 'SELECT COUNT(id) as id FROM personal_personal WHERE gender=4'
    total_other = Personal.objects.raw(sql)[0].id

    sql = 'SELECT COUNT(id) as id FROM personal_family WHERE 1'
    total_family = Personal.objects.raw(sql)[0].id
    sql = 'SELECT COUNT(id) as id FROM personal_house WHERE 1'
    total_house = Personal.objects.raw(sql)[0].id


    context = { 'total_person':total_person, 'total_male':total_male, 'total_female':total_female, 'total_third':total_third, 'total_other':total_other, 'total_family':total_family, 'total_house':total_house,

    }
    return render(request, 'design/index.html', context)
    #2 return HttpResponse(template.render(context, request))

@login_required(login_url='users:login')
def entry(request, person=0,house=None):
    request.session['myurl'] = request.path

    if person!=0:
        my_person = Personal.objects.get(pk = int(person))
        form = PersonalForm(request.POST or None, instance=my_person)
    else:
        form = PersonalForm(request.POST or None)
    if form.is_valid():
        person_saved = form.save()
        return redirect('formentry:people_status', status=1)
    return render(request, 'design/forms.html',{'form':form, 'user':request.user, 'personid':person, 'houseid':house})

@login_required(login_url='users:login')
def all_people(request, status=0):
    request.session['myurl'] = request.path
    a = Personal.objects.all()
    if status==1:
        status_name = "Saved"
    else:
        status_name = None
    return render(request, 'design/all.html', {'user':request.user,  'status':status_name, 'all':a})


@login_required(login_url='users:login')
def geo_entry(request, id=0):
    request.session['myurl'] = request.path
    if id !=0 :
        my_geo = GeoCode.objects.get(pk=int(id))
        form = GeoForm(request.POST or None, instance=my_geo)
    else:
        form = GeoForm(request.POST or None)
    if form.is_valid():
        geo_saved = form.save()
        return redirect('formentry:house_entry',geo=geo_saved.id, pid=0)
    return render (request,'entry_forms/geo.html',{'form':form, 'geoid':id})

@login_required(login_url='users:login')
def house_entry(request,geo=0, pid=0 ):
    request.session['myurl'] = request.path
    coordinate = GeoCode(pk=geo)
    try:
        my_house = House.objects.get(coordinates=coordinate)
        form = HouseForm(request.POST or None, instance=my_house)
    except House.DoesNotExist:
        if pid ==0:
            return redirect('formentry:family_details', house=0,  fid=0, geo=geo, pid=0)
        owner = Family(id=pid)
        my_house = House(coordinates=coordinate, owner=owner)
        form = HouseForm(request.POST or None, instance=my_house)
    add_others = True
    if form.is_valid():
        house_saved = form.save()
        return redirect('formentry:family_list', geo=geo)
    return render (request, 'entry_forms/house.html', {'form':form, 'personid':pid, 'geoid':geo, 'add_others':add_others})

@login_required(login_url='users:login')
def family_entry(request, house=0, fid=0, geo=0, pid=0):
    #fid = family head
    #pid = family person... if fid doesn't exist pid becomes main head
    request.session['myurl'] = request.path
    if fid==0:
        return redirect('formentry:house_head', coordinates=geo, pid=0)
    try:
        # family_head = Personal(id=fid)
        my_family = Family.objects.get(id=fid)
        # if my_family:
        #     return redirect('formentry:house_head', coordinates=geo, pid=0)
        if (request.POST or None) == None:
            return redirect('formentry:memberlist', family_id=fid)
        form = FamilyForm(request.POST or None, instance=my_family)
    except Family.DoesNotExist:
        family_head = Personal(id=fid)
        my_family = Family(person_head=family_head, myhouse=GeoCode(id=geo))
        form = FamilyForm(request.POST or None, instance=my_family)
    try:
        house_families = Family.objects.filter(myhouse=house)
    except:
        house_families = None
    if form.is_valid():
        family_saved =form.save()
        if house==0:
            return redirect ('formentry:house_entry', geo=geo, pid=family_saved.id)
        else:
            return redirect('formentry:family_details', house=house, fid=fid, geo=geo, pid=pid)
    return render(request, 'entry_forms/family.html',{'form':form, 'families':house_families, 'geo':geo, 'house':house, 'pid':pid, 'fid':fid})

@login_required(login_url='users:login')
def house_head_entry(request,coordinates=0, pid=0):
    request.session['myurl'] = request.path

    if pid != 0:
        my_person = Personal.objects.get(pk = int(pid))
        form = PersonalForm(request.POST or None, instance=my_person)
    else:
        form = PersonalForm(request.POST or None, request=request)
    if form.is_valid():
        person_saved = form.save(commit=False)
        person_saved.creator = request.user.username
        person_saved.save()
        return redirect('formentry:family_details', house=0, fid=person_saved.id, geo=coordinates, pid =0)

    # request.session['myurl'] = request.path
    return render(request, 'entry_forms/user_forms.html',{'form':form, 'user':request.user, 'personid':pid, 'geo':coordinates, 'form_next':'house'})

@login_required(login_url='users:login')
def family_list(request, geo):
    request.session['myurl'] = request.path

    GeoObject = GeoCode.objects.get(pk=geo)
    theHouse = House.objects.get(coordinates=GeoObject)
    # request.session['myurl'] = request.path
    ListofFamilies = Family.objects.filter(myhouse=GeoObject)
    return render(request, 'entry_forms/family_list.html',{
        'families':ListofFamilies,
        'geo':geo,
        'request':request,
        'house':theHouse,
    })


@login_required(login_url='users:login')
def member_list(request, family_id):
    request.session['myurl'] = request.path

    my_family = Family.objects.get(pk=family_id)
    request.session['myurl'] = request.path
    head = my_family.person_head
    try:
        ListofMembers = Relation.objects.filter(family=my_family)
    except Relation.DoesNotExist:
        ListofMembers = {}
    geo = my_family.myhouse.id # To reference back to family from member_list.html
    return render(request, 'entry_forms/family_member_list.html',{'members':ListofMembers, 'mooli':my_family.id, 'geo' : geo , 'head':head })

@login_required(login_url='users:login')
def relation_entry(request,mooli=0,child=0, entry=0):
    request.session['myurl'] = request.path

    try:
        mool_family = Family.objects.get(id=mooli)
        family_child = Personal.objects.get(id=child)
        if entry==0:
            form = PersonalForm(request.POST or None, instance=family_child)
            if form.is_valid():
                saved_entry = form.save()
                # message = "Saved"
            return render(request, 'entry_forms/user_forms.html',{'form':form, 'user':request.user, 'child':child, 'mooli':mooli, 'flag':'relation', 'personid':child,
            # 'message':message,
            })
    except Personal.DoesNotExist:
        form = PersonalForm(request.POST or None, request=request)
        if form.is_valid():
            # New Entry of PersonalForm
            # form = PersonForm(request.POST or None)
            saved_entry = form.save()
            return redirect('formentry:relation', mooli=mooli, child=saved_entry.id, entry=1)
        return render(request, 'entry_forms/user_forms.html',{'form':form, 'user':request.user, 'mooli':mooli, 'child':child, 'flag':'relation' })

    try:
        my_relation = Relation.objects.get(family=mool_family, person2=family_child)
        form = RelationForm(request.POST or None, instance=my_relation)
    except Relation.DoesNotExist:
        my_relation = Relation(family=mool_family, person2 =family_child)
        form = RelationForm(request.POST or None, instance=my_relation)
    if form.is_valid():
        relation_saved = form.save()
        return redirect('formentry:relation', mooli=mooli,  child=child, entry=0)
    return render(request, 'entry_forms/relation.html',{'form':form, 'mooli':mooli, 'child':child, 'entry':2})

@login_required(login_url='users:login')
def all_my_houses(request):
    request.session['myurl'] = request.path

    Houses = House.objects.all()
    # request.session['myurl'] = request.path
    HouseList = House.objects.all()
    return render(request, 'entry_forms/houselist.html',{'houses':HouseList, 'request':request})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth import login, logout


# Create your views here.
def index(request):
    context = {}
    return render(request,'users/index.html',context)


def login_view(request):
    #Loggin in the UsersConfig
    if request.method=='POST':
        #Do sth
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('formentry:index')

    else:
        #instantiate
        form = AuthenticationForm()

    return render(request,'users/index2.html',{'form':form})

def signup_view(request):
    # #Signup new user
    if request.method=='POST':
        #Do sth
        # logger.error('This was valid bro')
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # user = form.get_user
            login(request, user)
            return redirect('personal:index')

    else:
        #instantiate
        form = UserCreationForm()
        # form = 'This page is under Construction'

    return render(request,'users/index2.html',{'form':form})

def logout_view(request):
    logout(request)
    return redirect('users:login')

formentry/templates/design/all.html
{% extends 'design/index.html' %}


{% block content %}
  <div class="row">
      <div class="col-md-12">
          <div class="card ">
              <div class="card-header ">
                  <h4 class="card-title">Forms</h4>
                  <p class="card-category">{% if stat %}Your data has been {{stat}} {% endif %}</p>
              </div>
              <div class="card-body ">
                  <div id="form" >
                    <form action="{% url 'formentry:entry' %}" method="post">
                      {% csrf_token %}
                      {% for persons in all %}
                        <div class="form-group">
                            <a href = "{% url 'formentry:personid' person=persons.id %}">{{persons.full_name}}</a>
                        </div>
                    {% endfor %}
                    <input type="submit" value="submit"/>
                    </form>
                  </div>
              </div>
              <div class="card-footer ">
                  <div class="legend">
                      <i class="fa fa-circle text-info"></i> Open
                      <i class="fa fa-circle text-danger"></i> Bounce
                      <i class="fa fa-circle text-warning"></i> Unsubscribe
                  </div>
                  <hr>
                  <div class="stats">
                      <i class="fa fa-clock-o"></i> Campaign sent 2 days ago
                  </div>
              </div>
            </div>
          <div>
      </div>
  </div>
{% endblock %}

formentry/templates/design/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static '/assets/img/apple-icon.png' %}">
    <link rel="icon" type="image/png" href="{% static '/assets/img/favicon.ico' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>{% block title %}
    {% endblock %}</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet"/>
    <!-- CSS Files -->
    <link href="{% static '/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/css/light-bootstrap-dashboard.css' %}" rel="stylesheet" />
    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <script src="//rawgit.com/rubaxa/Sortable/master/Sortable.js"></script>
    <!--   Core JS Files   -->
    <script src="{% static 'assets/js/core/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
</head>

<body>
    <div class="wrapper">
        <div class="sidebar" data-image="{% static 'assets/img/sidebar-5.jpg' %}">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

        Tip 2: you can also add an image using data-image tag
    -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="http://www.kushmamun.gov.np" class="simple-text" style="font-family: Hind;">
                        कुश्मा - ७
                    </a>
                </div>
                <ul class="nav">
                    {% block nav %}
                    {% endblock %}
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg " color-on-scroll="500">
                <div class=" container-fluid  ">
                    <a class="navbar-brand" href="{% url 'formentry:index' %}"> Dashboard </a>
                    <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        {% block navbar %}
                        {% endblock %}
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            <div class="content">
                <div class="container-fluid">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            <footer class="footer">
                <div class="container">
                    {% block footer %}
                    {% endblock %}
                </div>
            </footer>
        </div>
    </div>

 <!--   Core JS Files   -->
 <!-- <script src="{% static 'assets/js/core/jquery.3.2.1.min.js' %}" type="text/javascript"></script> -->
 <script src="{% static 'assets/js/core/popper.min.js' %}" type="text/javascript"></script>
 <script src="{% static 'assets/js/core/bootstrap.min.js' %}" type="text/javascript"></script>
 <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
 <script src="{% static 'assets/js/plugins/bootstrap-switch.js' %}"></script>

 <!--  Chartist Plugin  -->
 <!-- <script src="{% static 'assets/js/plugins/chartist.min.js' %}"></script> -->
 <!--  Notifications Plugin    -->
 <script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>

<script src="{% static 'assets/js/light-bootstrap-dashboard.js' %}"></script>
<!-- Date Picker -->
<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>

<script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
</script>
{% block remaining-js %}
{% endblock %}
</body>
</html>

formentry/templates/design/basic_form.html
{% extends 'design/index.html' %}


{% block content %}
  <div class="row">
      <div class="col-md-12">
          <div class="card ">
              <div class="card-header ">
                  <h4 class="card-title">{% block card-title %} Forms {% endblock %}</h4>
                  <p class="card-category">{% if stat %}Your data has been {{stat}} {% endif %}</p>
              </div>
              <div class="card-body ">
                  <div id="form" >
                    <form action="{% url 'formentry:entry' %}" method="post">
                      {% csrf_token %}
                      {% for persons in all %}
                        <div class="form-group">
                            <a href = "{% url 'formentry:personid' person=persons.id %}">{{persons.full_name}}</a>
                        </div>
                    {% endfor %}
                    <input type="submit" value="submit"/>
                    </form>
                  </div>
              </div>
              <div class="card-footer ">
                  <div class="legend">
                      <i class="fa fa-circle text-info"></i> Open
                      <i class="fa fa-circle text-danger"></i> Bounce
                      <i class="fa fa-circle text-warning"></i> Unsubscribe
                  </div>
                  <hr>
                  <div class="stats">
                      <i class="fa fa-clock-o"></i> Campaign sent 2 days ago
                  </div>
              </div>
            </div>
          <div>
      </div>
  </div>
{% endblock %}

formentry/templates/design/forms.html
{% extends 'design/index.html' %}

{% load widget_tweaks %}

{% block content %}
  <div class="row">
      <div class="col-md-12">
          <div class="card ">
              <div class="card-header ">
                  <h4 class="card-title">{{formtitle}}</h4>
                  <p class="card-category">{{formdescription}}</p>
              </div>
              <div class="card-body ">
                  <div id="form" >
                    <form action="{% url 'formentry:personid' person=personid %}" method="post">
                      {% csrf_token %}
                      {% for field in form %}
                        <div class="form-group">
                            {{ field.errors }}
                            {{ field.label_tag }}
                            {% if field.name != 'pub_date' %}
                              {{ field |attr:"class:form-control" }}
                            {% else %}
                              {{ field |attr:"class:datetime-input form-control" }}
                            {% endif %}
                            {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}
                        </div>
                    {% endfor %}

                    <input type="submit" value="submit"/>
                  </form>
                  </div>
              </div>
              <div class="card-footer ">
                  <div class="legend">
                    {% if personid %}
                    <a class="btn btn-primary" href="{% url 'formentry:address_entry' id=personid pt=1 %}" role="button">Add Permanent Address Details</a>
                    <a class="btn btn-primary" href="{% url 'formentry:address_entry' id=personid pt=2 %}" role="button">Add Temporary Address Details</a>
                    <a class="btn btn-primary" href="{% url 'formentry:card_details' id=personid card=1 %}" role="button">Add Nagrikta Details</a>
                    <a class="btn btn-primary" href="{% url 'formentry:card_details' id=personid card=2 %}" role="button">Add License Details</a>
                    <a class="btn btn-primary" href="{% url 'formentry:card_details' id=personid card=3 %}" role="button">Add Passport Details</a>
                    <a class="btn btn-primary" href="{% url 'formentry:card_details' id=personid card=4 %}" role="button">Add Student Card Details</a>
                    <a class="btn btn-primary" href="{% url 'formentry:contact_details' id=personid contact=1 %}" role="button">Add Primary Contact Details</a>
                    <a class="btn btn-primary" href="{% url 'formentry:contact_details' id=personid contact=1 %}" role="button">Add Secondary Contact Details</a>
                    <a class="btn btn-primary" href="{% url 'formentry:social_details' id=personid media=1 %}" role="button">Add Facebook Details</a>

                    {% endif %}
                  </div>
                  <hr>

              </div>
            </div>
          <div>
      </div>
  </div>
{% endblock %}