api/urls.py
from django.urls import path
from api import views

urlpatterns = [
    path('values/', views.data_list),
    path('values/<int:pk>/', views.data_detail),
    path('form/<int:pk>/', views.form_data),
    path('form/<int:pk>/id/<int:person_id>/', views.person_form_data),
    path('qid/<int:question_id>/', views.question_form_data),
    path('question/<int:pk>/', views.form_question),
    path('choices/<int:pk>/', views.question_choices),
    path('type/<int:pk>/id/<int:person_id>/', views.person_data),
    path('type/<int:pk>/id/<int:person_id>/template', views.index),
    path('test', views.trypost),
    path('detail/<int:form_id>', views.detail),
]

parbatcms/urls.py
from django.conf.urls import include, url
# from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from formentry import views



urlpatterns = [
    # url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    # url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^personal/', include('personal.urls')),
    url(r'^forms/', include('formentry.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^post/', include('postform.urls')),
    # url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^$', views.index, name='index'),
    # url(r'^ajax/', include('mydajax.urls')),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    # url(r'^(?P<person_id>[0-9]+)/$', views.detail, name='detail'),
    # path('<int:person_id>/', views.detail, name='vote'),
]

#Namespacing URL Names
app_name = "users"

users/models.py
from django.db import models

# Create your models here.

class FormUser(models.Model):
    username = models.CharField('Username', max_length=20)
    password = models.CharField('Password', max_length=70)

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth import login, logout


# Create your views here.
def index(request):
    context = {}
    return render(request,'users/index.html',context)


def login_view(request):
    #Loggin in the UsersConfig
    if request.method=='POST':
        #Do sth
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('formentry:index')

    else:
        #instantiate
        form = AuthenticationForm()

    return render(request,'users/index2.html',{'form':form})

def signup_view(request):
    # #Signup new user
    if request.method=='POST':
        #Do sth
        # logger.error('This was valid bro')
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # user = form.get_user
            login(request, user)
            return redirect('personal:index')

    else:
        #instantiate
        form = UserCreationForm()
        # form = 'This page is under Construction'

    return render(request,'users/index2.html',{'form':form})

def logout_view(request):
    logout(request)
    return redirect('users:login')

users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
{%load static%}
<head>
	<title>Login Form</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{%static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{%static 'images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form">
					<span class="login100-form-title">
						YOu are logged in
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="email" placeholder="Email">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="#">
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>




<!--===============================================================================================-->
	<script src="{%static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{%static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{%static 'js/main.js' %}"></script>

</body>
</html>

users/templates/users/index2.html
<!DOCTYPE html>
<html lang="en">
{%load static%}
<head>
	<title>Login Form</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{%static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{%static 'images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method="post">
					<span class="login100-form-title">
						Member Login
					</span>
           <table>
          {{form}}
          {% csrf_token %}
        </table>
					<!-- <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="email" placeholder="Email">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div> -->

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="{% url 'users:signup' %}">
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>




<!--===============================================================================================-->
	<script src="{%static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{%static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{%static 'js/main.js' %}"></script>

</body>
</html>